name = "Bluntg"
version = "0.1.0"
defaultTargets = ["Bluntg", "bluntg", "unify"]

[[lean_lib]]
name = "Bluntg"

[[lean_exe]]
name = "bluntg"
root = "Main"

[[lean_exe]]
name = "unify"
root = "MainUnify"
